
// <copyright file="TestWorkflowContact.cs" company="Visa Inc">
// Copyright (c) 2017 All Rights Reserved
// </copyright>
// <author>Visa Inc</author>
// <date>4/27/2017 2:04:15 PM</date>
// <summary>Implements the TestWorkflowContact Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Text;
using System.ServiceModel;
using System.Threading.Tasks;
using System.Activities;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Workflow;
using System.Runtime.Serialization;

namespace Plugins2.WorkflowActivityLibrary1
{


    /// </summary>    
    public class TestWorkflowContact: WorkFlowActivityBase
    {

         
        #region Properties 
        //Property for Entity contact
        [RequiredArgument]
        [Input("This is a test.")] 
        [ReferenceTarget("contact")]
        public InArgument<EntityReference> Contact { get; set; }
        #endregion
        

        /// <summary>
        /// Executes the WorkFlow.
        /// </summary>
        /// <param name="crmWorkflowContext">The <see cref="LocalWorkflowContext"/> which contains the
        /// <param name="executionContext" > <see cref="CodeActivityContext"/>
        /// </param>       
        /// <remarks>
        /// For improved performance, Microsoft Dynamics 365 caches WorkFlow instances.
        /// The WorkFlow's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the WorkFlow. Also, multiple system threads
        /// could execute the WorkFlow at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in WorkFlows.
        /// </remarks>
        public override void ExecuteCRMWorkFlowActivity(CodeActivityContext executionContext, LocalWorkflowContext crmWorkflowContext)
        {                 

            if (crmWorkflowContext == null)
            {
                throw new ArgumentNullException("crmWorkflowContext");
            }

	        try
	        {
                // TODO: Implement your custom activity handling.
                Console.WriteLine("Executing the workflow!");
	        }
	        catch (FaultException<OrganizationServiceFault> e)
            {                
                // Handle the exception.
                throw e;
            }	  

        }
         

    }

}
